#ifndef _SETTINGS_PARAMS_
#define _SETTINGS_PARAMS_
#include <kamek.hpp>
#include <PulsarSystem.hpp>
#include <Config.hpp>

namespace Pulsar {
namespace UI { class SettingsPanel; }
namespace Settings {

class Params {
public:
    static const int pulsarPageCount = 4;
    static const int userPageCount = 4;
    static const int pageCount = pulsarPageCount + userPageCount;

    static const int maxRadioCount = 6; //per page, due to space
    static const int maxScrollerCount = 5; //per page, due to space
    static const int maxSettingBitCount = 5; //in bits

    //Pulsar and User
    static u8 radioCount[pageCount];
    static u8 scrollerCount[pageCount];
    static u8 buttonsPerPagePerRow[pageCount][maxRadioCount];
    static u8 optionsPerPagePerScroller[pageCount][maxScrollerCount];

};

//Contains all the settings. 
enum Type {
    SETTINGSTYPE_MENU,
    SETTINGSTYPE_RACE,
    SETTINGSTYPE_HOST,
    SETTINGSTYPE_OTTKO
};

//If you want to add settings to your packs, they go in this enum, and GetUserSettingValue should be used to obtain the value of a given setting
enum UserType {
    SETTINGSTYPE_AUDIO,
    SETTINGSTYPE_ITEM,
    SETTINGSTYPE_PHYSICS,
    SETTINGSTYPE_LAP
};

}//namespace Settings

//SETTINGS ENUM, for the page, DO NOT FORGET THE +6 for scrollers (see menu settings for example)
//Use these 3 for "u32 setting" in GetSettingValue, the return will be the value of the other enums
enum MenuSettings {
    SETTINGMENU_RADIO_FASTMENUS = 0,
    SETTINGMENU_RADIO_LAYOUT = 1,

    SETTINGMENU_SCROLL_BOOT = 0 + 6
};

enum RaceSettings {
    SETTINGRACE_RADIO_MII = 0,
    SETTINGRACE_RADIO_BATTLE = 1,
    SETTINGRACE_RADIO_BLUES = 2,
    SETTINGRACE_RADIO_SOM = 3,

    SETTINGRACE_SCROLL_SOM = 0 + 6
};

enum HostSettings {
    SETTINGHOST_RADIO_HOSTWINS = 0,
    SETTINGHOST_RADIO_CC = 1,
    SETTINGHOST_RADIO_ALLOW_MIIHEADS = 2,
    SETTINGHOST_RADIO_ALLOW_BRAKE = 3,
    SETTINGHOST_RADIO_DISREGARD = 4
};

enum OTTKOSettings {
    SETTINGOTT_VERSUS = 0,
    SETTINGOTT_ALLOWCHANGECOMBO = 1,
    SETTINGKO_ENABLED = 2,
    SETTINGKO_FINAL = 3,

    SETTINGKO_RACESPERKO = 1 + 6,
    SETTINGKO_KOPERRACE = 0 + 6
};

enum AudioSettings {
    SETTINGAUDIO_RADIO_MUSIC = 0,
    SETTINGAUDIO_RADIO_SPEEDUP = 1,
    SETTINGAUDIO_RADIO_LAPFINAL = 2,
    SETTINGAUDIO_RADIO_OTTMUTEPTANDPLAYERS = 3
};

enum ItemSettings {
    SETTINGITEM_RADIO_STARTENABLED = 0,

    SETTINGITEM_SCROLL_START = 2 + 6,
    SETTINGITEM_SCROLL_ROULETTE = 1 + 6,
    SETTINGITEM_SCROLL_CLOUD = 0 + 6
};

enum PhysSettings {
    SETTINGPHYS_RADIO_BRAKE = 0,
    SETTINGPHYS_RADIO_TURBO = 1,

    SETTINGPHYS_SCROLL_VEHICLESTATS = 2 + 6,
    SETTINGPHYS_SCROLL_SPEED = 1 + 6,
    SETTINGPHYS_SCROLL_GRAV = 0 + 6
};

enum LapSettings {
    SETTINGLAP_RADIO_CALC = 0,

    SETTINGLAP_SCROLL_LAPS = 1 + 6,
    SETTINGHOST_SCROLL_GP_RACES = 0 + 6
};

//MENU SETTINGS
enum MenuSettingFastMenus {
    MENUSETTING_FASTMENUS_DISABLED = 0x0,
    MENUSETTING_FASTMENUS_ENABLED = 0x1
};

enum MenuSettingLayout {
    MENUSETTING_LAYOUT_DEFAULT = 0x0,
    MENUSETTING_LAYOUT_ALPHABETICAL = 0x1
};

enum MenuSettingBoot {
    MENUSETTING_BOOT_DISABLED,
    MENUSETTING_BOOT_L1,
    MENUSETTING_BOOT_L2,
    MENUSETTING_BOOT_L3,
    MENUSETTING_BOOT_L4
};

//RACE SETTINGS
enum RaceSettingMII {
    RACESETTING_MII_DISABLED = 0x0,
    RACESETTING_MII_ENABLED = 0x1
};

enum RaceSettingBATTLE {
    RACESETTING_BATTLE_GLITCH_DISABLED = 0x0,
    RACESETTING_BATTLE_GLITCH_ENABLED = 0x1
};

enum RaceSettingBLUES {
    RACESETTING_DRAGGABLE_BLUES_DISABLED = 0x0,
    RACESETTING_DRAGGABLE_BLUES_ENABLED = 0x1
};

enum RaceSettingSOM {
    RACESETTING_SOM_LEFT = 0x0,
    RACESETTING_SOM_RIGHT = 0x1,
    RACESETTING_SOM_DISABLED = 0x2
};

enum RaceSettingSOMDigits {
    RACESETTING_SOM_DIGITS_0,
    RACESETTING_SOM_DIGITS_1,
    RACESETTING_SOM_DIGITS_2,
    RACESETTING_SOM_DIGITS_3,
};

//HOST SETTINGS
enum HostSettingHAW {
    HOSTSETTING_HOSTWINS_DISABLED,
    HOSTSETTING_HOSTWINS_ENABLED,
    HOSTSETTING_HOSTWINS_INORDER
};

enum HostSettingHostCC {
    HOSTSETTING_CC_150,
    HOSTSETTING_CC_MIRROR,
    HOSTSETTING_CC_NORMAL, // Reordered as setting is unused
    HOSTSETTING_CC_100 // These settings are still implemented in case our engine class system improves
};

enum HostSettingMiiHeads {
    HOSTSETTING_ALLOW_MIIHEADS_ENABLED,
    HOSTSETTING_ALLOW_MIIHEADS_DISABLED
};

enum HostSettingLolBrake {
    HOSTSETTING_ALLOW_LOLPACK_BRAKE_ENABLED,
    HOSTSETTING_ALLOW_LOLPACK_BRAKE_DISABLED
};

enum HostSettingDisregard {
    HOSTSETTING_DISREGARD_DISABLED,
    HOSTSETTING_DISREGARD_ENABLED
};

//OTTKOSETTINGS
enum OTTSetting {
    OTTSETTING_DISABLED,
    OTTSETTING_ENABLED
};

enum OTTSettingCombo {
    OTTSETTING_COMBO_DISABLED,
    OTTSETTING_COMBO_ENABLED
};

enum KOSettingEnabled {
    KOSETTING_DISABLED,
    KOSETTING_ENABLED,
};
enum KOSettingFINAL {
    KOSETTING_FINAL_DISABLED,
    KOSETTING_FINAL_ALWAYS,
};
enum KOSettingKOPerRace {
    KOSETTING_KOPERRACE_1,
    KOSETTING_KOPERRACE_2,
    KOSETTING_KOPERRACE_3,
    KOSETTING_KOPERRACE_4
};

enum KOSettingRacesPerKO {
    KOSETTING_RACESPERKO_1,
    KOSETTING_RACESPERKO_2,
    KOSETTING_RACESPERKO_3,
    KOSETTING_RACESPERKO_4
};

//USER-AUDIOSETTINGS
enum AudioMusic {
    AUDIOSETTING_MUSIC_DEFAULT,
    AUDIOSETTING_MUSIC_DISABLEALL,
    AUDIOSETTING_MUSIC_DISABLERACE
};

enum AudioSpeedup {
    AUDIOSETTING_SPEEDUP_DISABLED,
    AUDIOSETTING_SPEEDUP_ENABLED
};

enum AudioFinalPercent {
    AUDIOSETTING_LAPFINAL_ENABLED,
    AUDIOSETTING_LAPFINAL_DISABLED
};

enum AudioOTTmute {
    AUDIOSETTING_OTT_DISABLED,
    AUDIOSETTING_OTT_ENABLED
};

//USER-ITEMSETTINGS
enum ItemStartToggle {
    ITEMSETTING_START_DISABLED,
    ITEMSETTING_START_ENABLED
};

enum ItemCloudBehaviour {
    ITEMSETTING_CLOUDBEHAVIOUR_VANILLA,
    ITEMSETTING_CLOUDBEHAVIOUR_REPEAT
};

enum ItemStart {
    ITEMSETTING_START_3MUS,
    ITEMSETTING_START_GMUS,
    ITEMSETTING_START_FEAT,
    ITEMSETTING_START_3FEA,
    ITEMSETTING_START_STAR,
    ITEMSETTING_START_MEGA,
    ITEMSETTING_START_CLOU,
    ITEMSETTING_START_GREN,
    ITEMSETTING_START_3GRN,
    ITEMSETTING_START_REDS,
    ITEMSETTING_START_3RED,
    ITEMSETTING_START_BLUE,
    ITEMSETTING_START_BANA,
    ITEMSETTING_START_3BNA,
    ITEMSETTING_START_FIBX,
    ITEMSETTING_START_3FIB,
    ITEMSETTING_START_BOMB,
    ITEMSETTING_START_BLPR,
    //ITEMSETTING_START_GHST,
    ITEMSETTING_START_POWB,
    ITEMSETTING_START_BILL,
    ITEMSETTING_START_SHOK,
    ITEMSETTING_START_NONE,
    ITEMSETTING_START_MUSH
};

enum ItemRoulette {
    ITEMSETTING_ROULETTE_STANDARD,
    ITEMSETTING_ROULETTE_MUSHROOMS,
    ITEMSETTING_ROULETTE_RANDOM,
    ITEMSETTING_ROULETTE_DEBALANCED,
    ITEMSETTING_ROULETTE_VANILLA
};

enum ItemCloud {
    ITEMSETTING_CLOUD_SHOCK,
    ITEMSETTING_CLOUD_MEGA,
    ITEMSETTING_CLOUD_STAR,
    ITEMSETTING_CLOUD_FEATHER,
    ITEMSETTING_CLOUD_DEATH,
    ITEMSETTING_CLOUD_BLOOPER,
    ITEMSETTING_CLOUD_MEGASTAR,
    ITEMSETTING_CLOUD_SHOCKBLOOPER,
    ITEMSETTING_CLOUD_SHOCKMEGA,
    ITEMSETTING_CLOUD_MEGASHOCK
};

//USER-PHYSICSSETTINGS
enum PhysicsBrake {
    PHYSSETTING_BRAKE_STANDARD,
    PHYSSETTING_BRAKE_DISABLED,
    PHYSSETTING_BRAKE_ENABLED
};

enum PhysicsTurbo {
    PHYSSETTING_TURBO_VANILLA,
    PHYSSETTING_TURBO_UMT,
    PHYSSETTING_TURBO_MKDS
};

enum PhysicsSpeed {
    PHYSSETTING_SPEED_100,
    PHYSSETTING_SPEED_110,
    PHYSSETTING_SPEED_125,
    PHYSSETTING_SPEED_150,
    PHYSSETTING_SPEED_175,
    PHYSSETTING_SPEED_200,
    PHYSSETTING_SPEED_300,
    PHYSSETTING_SPEED_500,
    PHYSSETTING_SPEED_999,
    PHYSSETTING_SPEED_070,
    PHYSSETTING_SPEED_080,
    PHYSSETTING_SPEED_090
};

enum PhysicsGravity {
    PHYSSETTING_GRAVITY_100,
    PHYSSETTING_GRAVITY_110,
    PHYSSETTING_GRAVITY_125,
    PHYSSETTING_GRAVITY_150,
    PHYSSETTING_GRAVITY_200,
    PHYSSETTING_GRAVITY_500,
    PHYSSETTING_GRAVITY_025,
    PHYSSETTING_GRAVITY_050,
    PHYSSETTING_GRAVITY_075,
    PHYSSETTING_GRAVITY_090
};

//USER-LAPSETTINGS
enum LapCalc {
    LAPSETTING_CALC_MATHS,
    LAPSETTING_CALC_EXCLUDE,
    LAPSETTING_CALC_FORCE
};

enum LapLaps {
    LAPSETTING_LAPS_3,
    LAPSETTING_LAPS_4,
    LAPSETTING_LAPS_5,
    LAPSETTING_LAPS_6,
    LAPSETTING_LAPS_7,
    LAPSETTING_LAPS_8,
    LAPSETTING_LAPS_9,
    LAPSETTING_LAPS_1,
    LAPSETTING_LAPS_2
};

enum LapRaces {
    LAPSETTING_GP_RACES_4,
    LAPSETTING_GP_RACES_6,
    LAPSETTING_GP_RACES_8,
    LAPSETTING_GP_RACES_12,
    LAPSETTING_GP_RACES_32,
    LAPSETTING_GP_RACES_64,
    LAPSETTING_GP_RACES_256,
    LAPSETTING_GP_RACES_0,
    LAPSETTING_GP_RACES_1,
    LAPSETTING_GP_RACES_2,
    LAPSETTING_GP_RACES_3
};

}//namespace Pulsar



#endif