#ifndef _SETTINGS_PARAMS_
#define _SETTINGS_PARAMS_
#include <kamek.hpp>
#include <PulsarSystem.hpp>
#include <Config.hpp>

namespace Pulsar {
namespace UI { class SettingsPanel; }
namespace Settings {

class Params {
public:
    static const int pulsarPageCount = 5;
    static const int userPageCount = 1;
    static const int pageCount = pulsarPageCount + userPageCount;

    static const int maxRadioCount = 6; //per page, due to space
    static const int maxScrollerCount = 5; //per page, due to space

    //Pulsar and User
    static u8 radioCount[pageCount];
    static u8 scrollerCount[pageCount];
    static u8 buttonsPerPagePerRow[pageCount][maxRadioCount];
    static u8 optionsPerPagePerScroller[pageCount][maxScrollerCount];

};

//Contains all the settings. 
enum Type {
    SETTINGSTYPE_MENU,
    SETTINGSTYPE_RACE,
    SETTINGSTYPE_HOST,
    SETTINGSTYPE_KO,
    SETTINGSTYPE_OTT
};

//If you want to add settings to your packs, they go in this enum, and GetUserSettingValue should be used to obtain the value of a given setting
enum UserType {
    SETTINGSTYPE_GAME,
    SETTINGSTYPE_TC
};

}//namespace Settings

//SETTINGS ENUM, for the page, DO NOT FORGET THE +6 for scrollers (see menu settings for example)
//Use these 3 for "u32 setting" in GetSettingValue, the return will be the value of the other enums
enum MenuSettings {
    SETTINGMENU_RADIO_FASTMENUS = 0,
    SETTINGMENU_RADIO_LAYOUT = 1,
    SETTINGMENU_RADIO_MUSIC = 2,
    SETTINGMENU_SCROLL_BOOT = 0 + 6
};

enum RaceSettings {
    SETTINGRACE_RADIO_MII,
    SETTINGRACE_RADIO_SPEEDUP,
    SETTINGRACE_RADIO_BATTLE,
    SETTINGRACE_RADIO_BLUES,
    SETTINGRACE_RADIO_SOM,

    SETTINGRACE_SCROLL_SOM = 0 + 6
};

enum HostSettings {
    SETTINGHOST_RADIO_HOSTWINS = 0,
    SETTINGHOST_RADIO_CC = 1,
    SETTINGHOST_ALLOW_MIIHEADS = 2,
    SETTINGHOST_ALLOW_LOLPACK_BRAKE = 3,

    SETTINGHOST_SCROLL_GP_RACES = 0 + 6
};

enum KOSettings {
    SETTINGKO_ENABLED = 0,
    SETTINGKO_FINAL = 1,

    SETTINGKO_KOPERRACE = 0 + 6,
    SETTINGKO_RACESPERKO = 1 + 6
};

enum OTTSettings {
    SETTINGOTT_VERSUS = 0,
    SETTINGOTT_ALLOWCHANGECOMBO = 1,
    SETTINGOTT_ALLOWUMTS = 2,
    SETTINGOTT_MUTEPTANDPLAYERS = 3,

    SETTINGOTT_TTITEMCOUNT = 0 + 6,
    SETTINGOTT_TTITEM = 1 + 6
};

enum GAMESettings {
    SETTINGGAME_RADIO_BRAKE = 0,
    SETTINGGAME_RADIO_LAPSTYPE = 1,

    SETTINGGAME_SCROLL_ROULETTE = 0 + 6,
    SETTINGGAME_SCROLL_SPEEDMOD = 1 + 6,
    SETTINGGAME_SCROLL_LAPCOUNT = 2 + 6
};

enum TCSettings {
    SETTINGTC_TC_EFFECT = 0,
    SETTINGTC_TC_TYPE = 1 + 6,
    SETTINGTC_TC_EXTRATYPE = 0 + 6
};

//MENU SETTINGS
enum MenuSettingFastMenus {
    MENUSETTING_FASTMENUS_DISABLED = 0x0,
    MENUSETTING_FASTMENUS_ENABLED = 0x1
};

enum MenuSettingLayout {
    MENUSETTING_LAYOUT_DEFAULT = 0x0,
    MENUSETTING_LAYOUT_ALPHABETICAL = 0x1
};

enum MenuSettingMusic {
    MENUSETTING_MUSIC_DEFAULT = 0x0,
    MENUSETTING_MUSIC_DISABLE_ALL = 0x1,
    MENUSETTING_MUSIC_DISABLE_RACE = 0x2
};

enum MenuSettingBoot {
    MENUSETTING_BOOT_DISABLED,
    MENUSETTING_BOOT_L1,
    MENUSETTING_BOOT_L2,
    MENUSETTING_BOOT_L3,
    MENUSETTING_BOOT_L4
};

//RACE SETTINGS
enum RaceSettingMII {
    RACESETTING_MII_DISABLED = 0x0,
    RACESETTING_MII_ENABLED = 0x1
};

enum RaceSettingSPEEDUP {
    RACESETTING_SPEEDUP_DISABLED = 0x0,
    RACESETTING_SPEEDUP_ENABLED = 0x1
};

enum RaceSettingBATTLE {
    RACESETTING_BATTLE_GLITCH_DISABLED = 0x0,
    RACESETTING_BATTLE_GLITCH_ENABLED = 0x1
};

enum RaceSettingBLUES {
    RACESETTING_DRAGGABLE_BLUES_DISABLED = 0x0,
    RACESETTING_DRAGGABLE_BLUES_ENABLED = 0x1
};

enum RaceSettingSOM {
    RACESETTING_SOM_LEFT = 0x0,
    RACESETTING_SOM_RIGHT = 0x1,
    RACESETTING_SOM_DISABLED = 0x2
};

enum RaceSettingSOMDigits {
    HOSTSETTING_SOM_DIGITS_0,
    HOSTSETTING_SOM_DIGITS_1,
    HOSTSETTING_SOM_DIGITS_2,
    HOSTSETTING_SOM_DIGITS_3,
};

//HOST SETTINGS
enum HostSettingHAW {
    HOSTSETTING_HOSTWINS_DISABLED,
    HOSTSETTING_HOSTWINS_ENABLED,
    HOSTSETTING_HOSTWINS_INORDER
};

enum HostSettingHostCC {
    HOSTSETTING_CC_NORMAL,
    HOSTSETTING_CC_150,
    HOSTSETTING_CC_100,
    HOSTSETTING_CC_MIRROR
};

enum HostSettingMiiHeads {
    HOSTSETTING_ALLOW_MIIHEADS_ENABLED,
    HOSTSETTING_ALLOW_MIIHEADS_DISABLED
};

enum HostSettingLolBrake {
    HOSTSETTING_ALLOW_LOLPACK_BRAKE_ENABLED,
    HOSTSETTING_ALLOW_LOLPACK_BRAKE_DISABLED
};

enum HostSettingGPRACES {
    HOSTSETTING_GP_RACES_4,
    HOSTSETTING_GP_RACES_6,
    HOSTSETTING_GP_RACES_8,
    HOSTSETTING_GP_RACES_12,
    HOSTSETTING_GP_RACES_32,
    HOSTSETTING_GP_RACES_64,
    HOSTSETTING_GP_RACES_256,
    HOSTSETTING_GP_RACES_ALL,
    HOSTSETTING_GP_RACES_1,
    HOSTSETTING_GP_RACES_2,
    HOSTSETTING_GP_RACES_3
};

//KOSETTINGS
enum KOSettingEnabled {
    KOSETTING_DISABLED,
    KOSETTING_ENABLED,
};
enum KOSettingFINAL {
    KOSETTING_FINAL_DISABLED,
    KOSETTING_FINAL_ALWAYS,
};
enum KOSettingKOPerRace {
    KOSETTING_KOPERRACE_1,
    KOSETTING_KOPERRACE_2,
    KOSETTING_KOPERRACE_3,
    KOSETTING_KOPERRACE_4
};

enum KOSettingRacesPerKO {
    KOSETTING_RACESPERKO_1,
    KOSETTING_RACESPERKO_2,
    KOSETTING_RACESPERKO_3,
    KOSETTING_RACESPERKO_4
};
//KOSETTINGS

//OTTSETTINGS //Largely edited by lolpack
enum OTTSetting {
    OTTSETTING_DISABLED,
    OTTSETTING_ENABLED
};

enum OTTSettingCombo {
    OTTSETTING_COMBO_DISABLED,
    OTTSETTING_COMBO_ENABLED
};

enum OTTSettingUMTs {
    OTTSETTING_UMTS_DISABLED,
    OTTSETTING_UMTS_ENABLED
};

enum OTTSettingMutePtAndPlayers { // This setting didn't exist before?? Only putting this here as a placeholder because I need to add scrolls
    OTTSETTING_MUTEPTANDPLAYERS_DISABLED,
    OTTSETTING_MUTEPTANDPLAYERS_ENABLED
};

enum OTTSettingItemcount {
    OTTSETTING_ITEMCOUNT_STANDARD,
    OTTSETTING_ITEMCOUNT_1,
    OTTSETTING_ITEMCOUNT_2,
    OTTSETTING_ITEMCOUNT_3,
    OTTSETTING_ITEMCOUNT_4,
    OTTSETTING_ITEMCOUNT_5,
    OTTSETTING_ITEMCOUNT_6,
    OTTSETTING_ITEMCOUNT_7,
    OTTSETTING_ITEMCOUNT_8,
    OTTSETTING_ITEMCOUNT_9,
    OTTSETTING_ITEMCOUNT_10,
    OTTSETTING_ITEMCOUNT_15,
    OTTSETTING_ITEMCOUNT_25,
    OTTSETTING_ITEMCOUNT_50,
    OTTSETTING_ITEMCOUNT_9999,
    OTTSETTING_ITEMCOUNT_CALCULATED
};

enum OTTSettingItem {
    OTTSETTING_ITEM_MUSHROOM,
    OTTSETTING_ITEM_FEATHER,
    OTTSETTING_ITEM_STAR,
    OTTSETTING_ITEM_MEGA,
    OTTSETTING_ITEM_GOLDEN,
    OTTSETTING_ITEM_TC,
    OTTSETTING_ITEM_BULLET
};
//OTTSETTINGS

//USER-GAMEPLAYSETTINGS
enum GAMEBrakeDrift {
    GAMESETTING_200_STANDARD,
    GAMESETTING_200_DISABLED,
    GAMESETTING_200_ENABLED
};
enum GAMELapType {
    GAMESETTING_LAPTYPE_MATHS,
    GAMESETTING_LAPTYPE_EXCLUDE,
    GAMESETTING_LAPTYPE_FORCE,
    GAMESETTING_LAPTYPE_DEBUGEXPONENT
};
enum GAMEItemRoulette {
    GAMESETTING_ITEMS_DEFAULT,
    GAMESETTING_ITEMS_MUSHROOMS,
    GAMESETTING_ITEMS_RANDOM,
    GAMESETTING_ITEMS_DEATH,
    GAMESETTING_ITEMS_ITEMRAIN,
    GAMESETTING_ITEMS_SHROOMGLITCH
};
enum GAMESpeedMod {
    GAMESETTING_SPEED_100,
    GAMESETTING_SPEED_110,
    GAMESETTING_SPEED_125,
    GAMESETTING_SPEED_150,
    GAMESETTING_SPEED_175,
    GAMESETTING_SPEED_200,
    GAMESETTING_SPEED_300,
    GAMESETTING_SPEED_500,
    GAMESETTING_SPEED_999,
    GAMESETTING_SPEED_070,
    GAMESETTING_SPEED_080,
    GAMESETTING_SPEED_090
};
enum GAMELapCount {
    GAMESETTING_LAPS_3,
    GAMESETTING_LAPS_4,
    GAMESETTING_LAPS_5,
    GAMESETTING_LAPS_6,
    GAMESETTING_LAPS_7,
    GAMESETTING_LAPS_8,
    GAMESETTING_LAPS_9,
    GAMESETTING_LAPS_1,
    GAMESETTING_LAPS_2
};

//TCSettings
enum TCSettingTCEFFECT {
    TCSETTING_TCEFFECT_SINGLE,
    TCSETTING_TCEFFECT_DOUBLE
};
enum TCSettingTCTYPE {
    TCSETTING_TC_DEFAULT,
    TCSETTING_TC_MEGA,
    TCSETTING_TC_STAR,
    TCSETTING_TC_BLOOPER
};

enum SettingTCEXTRATYPE {
    TCSETTING_EXTRATC_DEFAULT,
    TCSETTING_EXTRATC_MEGA,
    TCSETTING_EXTRATC_STAR,
    TCSETTING_EXTRATC_BLOOPER
};
//USER-GAMEPLAYSETTINGS

}//namespace Pulsar



#endif